[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    'hot-chain-svg/=contracts/',
    'hot-chain-svg/scripts/=contracts/scripts/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/'
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
